version: "3.9"

services:
    db:
        image: postgres:12
        env_file:
            - backend/.env
        volumes:
            - app-db-data:/var/lib/postgresql/data/pgdata
        environment:
            PGDATA: "/var/lib/postgresql/data/pgdata"
        restart: unless-stopped

    backend:
        build:
            context: ./backend
            args:
                INSTALL_DEV: ${INSTALL_DEV-false}
        depends_on:
            - db
        env_file:
            - backend/.env
        environment:
            WAIT_HOSTS: db:5432
        restart: unless-stopped

    frontend:
        build: ./frontend
        depends_on:
            - backend
        restart: unless-stopped
        ports:
            - ${PORT-3000}:80

volumes:
    app-db-data:
